name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: DeLaGuardo/setup-graalvm@latest
        # alternative for getting regular Java: actions/setup-java@v1
        with:
          graalvm-version: '20.0.0.java11'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: "latest" 
        
      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Run tests
        run: clj -A:test
